# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "Gnarks-Gradle-Workflow", "main" ]
  pull_request:
    branches: [ "Gnarks-Gradle-Workflow", "main" ]



jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      DISPLAY: ":99.0"
      # Set a display for Xvfb

    services:
      xvfb:
        image: selenium/standalone-chrome:latest
        options: -e VNC_SERVER=true -e VNC_PORT=5900

    runs-on: ${{ matrix.os }}
    permissions:
      artifact-metadata: write
      contents: read
    steps:

    - name: Start Xvfb
      run: Xvfb $DISPLAY -ac -screen 0 1600x1200x24 > /dev/null 2>&1 &


    - uses: actions/checkout@v6
    - name: Set up JDK 25
      uses: actions/setup-java@v5
      with:
        java-version: '25'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    # - name: Setup Gradle
    #   uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    # - name: Build with Gradle Wrapper
    #   run: gradle build

    # NOTE: The Gradle Wrapper is the default and recommended way to run Gradle (https://docs.gradle.org/current/userguide/gradle_wrapper.html).
    # If your project does not have the Gradle Wrapper configured, you can use the following configuration to run Gradle with a specified version.
    #
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      with:
        gradle-version: '9.1.0'

    - name: Build with Gradle 9.1.0
      run: gradle build

    - uses: actions/upload-artifact@v6
      with:
        # Name of the artifact to upload.
        # Optional. Default is 'artifact'
        name: TestReport

        # A file, directory or wildcard pattern that describes what to upload
        # Required.
        path: app/build/reports/tests

        # The desired behavior if no files are found using the provided path.
        # Available Options:
        #   warn: Output a warning but do not fail the action
        #   error: Fail the action with an error message
        #   ignore: Do not output any warnings or errors, the action does not fail
        # Optional. Default is 'warn'
        if-no-files-found:

        # Duration after which artifact will expire in days. 0 means using default retention.
        # Minimum 1 day.
        # Maximum 90 days unless changed from the repository settings page.
        # Optional. Defaults to repository settings.
        retention-days:

        # The level of compression for Zlib to be applied to the artifact archive.
        # The value can range from 0 to 9.
        # For large files that are not easily compressed, a value of 0 is recommended for significantly faster uploads.
        # Optional. Default is '6'
        compression-level:

        # If true, an artifact with a matching name will be deleted before a new one is uploaded.
        # If false, the action will fail if an artifact for the given name already exists.
        # Does not fail if the artifact does not exist.
        # Optional. Default is 'false'
        overwrite:

        # Whether to include hidden files in the provided path in the artifact
        # The file contents of any hidden files in the path should be validated before
        # enabled this to avoid uploading sensitive information.
        # Optional. Default is 'false'
        include-hidden-files:

