
name : pmd code analysis

on:
  push:
    branches: [ "Gnarks-pmd", "main" ]
  pull_request:
    branches: [ "Gnarks-pmd", "main" ]




jobs:
  pmd:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '24'
      - uses: pmd/pmd-github-action@v2
        with:
          sourcePath: './app/src/main/java/org/example/'
          rulesets: 'category/java/errorprone.xml'
      - name: Fail build if there are violations
        if: steps.pmd.outputs.violations == 2
        run: exit 1

