
name : pmd code analysis

on:
  push:
    branches: [ "Gnarks-pmd", "main" ]
  pull_request:
    branches: [ "Gnarks-pmd", "main" ]




permissions:
  contents: read

jobs:
  pmd:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'temurin'
          java-version: '24'
      - uses: pmd/pmd-github-action@d9c1f3c5940cbf5923f1354e83fa858b4496ebaa # v2.0.0
        with:
          analyzeModifiedFilesOnly: "false"
          sourcePath: 'app/src/main/java'
          rulesets: 'category/java/errorprone.xml'
      - name: Fail build if there are violations
        if: steps.pmd.outputs.violations >= 50
        run: exit 1
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@9e907b5e64f6b83e7804b09294d44122997950d6 # v4.32.3
        with:
          sarif_file: pmd-report.sarif

